// examples.js - Comprehensive array of form examples for CRM, ERP, Productivity, HR, Finance, Supply Chain, etc.
// Use Persian labels; dependencies for deep chaining.

export default [
  // CRM Examples (1-15)
  {
    name: 'مشتریان',
    description: 'اطلاعات پایه مشتریان',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام', required: true },
      { id: '2', type: 'text', label: 'نام خانوادگی', required: true },
      { id: '3', type: 'text', label: 'ایمیل', required: true },
      { id: '4', type: 'text', label: 'تلفن', required: false },
      { id: '5', type: 'text', label: 'آدرس', required: false },
      {
        id: '6',
        type: 'select',
        label: 'وضعیت',
        options: ['فعال', 'غیرفعال'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'سرنخ‌ها',
    description: 'مدیریت سرنخ‌های فروش',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام سرنخ', required: true },
      {
        id: '2',
        type: 'entity_reference',
        label: 'مرتبط با مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: false,
      },
      { id: '3', type: 'text', label: 'منبع', required: true },
      { id: '4', type: 'date', label: 'تاریخ تماس', required: true },
      {
        id: '5',
        type: 'select',
        label: 'اولویت',
        options: ['بالا', 'متوسط', 'پایین'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'فرصت‌ها',
    description: 'پیگیری فرصت‌های فروش',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
      {
        id: '2',
        type: 'entity_reference',
        label: 'سرنخ',
        targetFormType: '{step_2_id}',
        displayField: 'نام سرنخ',
        required: false,
      },
      { id: '3', type: 'text', label: 'عنوان', required: true },
      { id: '4', type: 'currency', label: 'ارزش', required: true },
      {
        id: '5',
        type: 'select',
        label: 'مرحله',
        options: ['پیشنهاد', 'مذاکره', 'بسته'],
        required: true,
      },
    ],
    itemFields: [
      { id: '6', type: 'text', label: 'اقدام', required: true },
      { id: '7', type: 'date', label: 'موعد', required: true },
    ],
    dependencies: [
      { from: 'مشتریان', step: '1' },
      { from: 'سرنخ‌ها', step: '2' },
    ],
  },
  {
    name: 'تماس‌ها',
    description: 'تعاملات با مشتریان',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'text', label: 'نوع تماس', required: true },
      { id: '3', type: 'date', label: 'تاریخ', required: true },
      { id: '4', type: 'textarea', label: 'یادداشت', required: false },
    ],
    itemFields: [
      {
        id: '5',
        type: 'select',
        label: 'نتیجه',
        options: ['موفق', 'ناموفق', 'دنباله'],
        required: true,
      },
    ],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'حساب‌ها',
    description: 'حساب‌های سازمانی',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام شرکت', required: true },
      { id: '2', type: 'text', label: 'صنعت', required: true },
      { id: '3', type: 'currency', label: 'درآمد سالانه', required: true },
      {
        id: '4',
        type: 'select',
        label: 'نوع',
        options: ['B2B', 'B2C'],
        required: true,
      },
      {
        id: '5',
        type: 'entity_reference',
        label: 'مدیر',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'کمپین‌ها',
    description: 'کمپین‌های بازاریابی',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'نام کمپین', required: true },
      { id: '2', type: 'date', label: 'شروع', required: true },
      { id: '3', type: 'date', label: 'پایان', required: true },
      { id: '4', type: 'currency', label: 'بودجه', required: true },
    ],
    itemFields: [
      { id: '5', type: 'text', label: 'کانال', required: true },
      { id: '6', type: 'text', label: 'هدف', required: true },
      { id: '7', type: 'number', label: 'هزینه', required: true },
    ],
    dependencies: [],
  },
  {
    name: 'پیشنهادها',
    description: 'پیشنهادهای فروش',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      { id: '3', type: 'text', label: 'شماره', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'کالا', required: true },
      { id: '5', type: 'currency', label: 'قیمت پیشنهادی', required: true },
      { id: '6', type: 'text', label: 'شرایط', required: false },
    ],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'معاملات',
    description: 'مدیریت معاملات',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'فرصت',
        targetFormType: '{step_3_id}',
        displayField: 'عنوان',
        required: true,
      },
      {
        id: '2',
        type: 'select',
        label: 'نوع معامله',
        options: ['خرید', 'فروش'],
        required: true,
      },
      { id: '3', type: 'currency', label: 'مبلغ', required: true },
      { id: '4', type: 'date', label: 'تاریخ بسته', required: true },
      { id: '5', type: 'text', label: 'یادداشت', required: false },
    ],
    itemFields: [],
    dependencies: [{ from: 'فرصت‌ها', step: '3' }],
  },
  {
    name: 'فعالیت‌ها',
    description: 'فعالیت‌های روزانه',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'text', label: 'نوع فعالیت', required: true },
      { id: '3', type: 'date', label: 'زمان', required: true },
      { id: '4', type: 'textarea', label: 'جزئیات', required: false },
    ],
    itemFields: [],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'مناطق',
    description: 'تقسیم‌بندی مناطق فروش',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام منطقه', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مدیر منطقه',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'لوله‌کشی فروش',
    description: 'مراحل فروش',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام مرحله', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرحله قبلی',
        targetFormType: '{step_1_id}',
        displayField: 'نام مرحله',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'لوله‌کشی فروش', step: '1' }],
  },
  {
    name: 'فیلدهای سفارشی',
    description: 'فیلدهای اضافی CRM',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام فیلد', required: true },
      {
        id: '2',
        type: 'select',
        label: 'نوع',
        options: ['text', 'date'],
        required: true,
      },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرتبط با فرم',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'فرم‌های سفارشی', step: '1' }],
  },
  {
    name: 'داشبورد تحلیلی',
    description: 'نمایش آمار CRM',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'از تاریخ', required: true },
      { id: '2', type: 'date', label: 'تا تاریخ', required: true },
      {
        id: '3',
        type: 'select',
        label: 'نوع گزارش',
        options: ['فروش', 'مشتریان'],
        required: true,
      },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'معیار', required: true },
      { id: '5', type: 'number', label: 'مقدار', required: true },
    ],
    dependencies: [],
  },
  {
    name: 'قالب‌های ایمیل',
    description: 'قالب‌های ارتباطی',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان', required: true },
      { id: '2', type: 'textarea', label: 'محتوا', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرتبط با نوع',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'انواع ایمیل', step: '1' }],
  },
  {
    name: 'انواع ایمیل',
    description: 'دسته‌بندی ایمیل‌ها',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام نوع', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'انتصاب وظایف',
    description: 'تخصیص وظایف به تیم',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'وظیفه',
        targetFormType: '{step_1_id}',
        displayField: 'عنوان',
        required: true,
      },
      {
        id: '2',
        type: 'entity_reference',
        label: 'کاربر',
        targetFormType: '{step_2_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '3', type: 'date', label: 'موعد', required: true },
    ],
    itemFields: [],
    dependencies: [
      { from: 'وظایف', step: '1' },
      { from: 'کاربران', step: '2' },
    ],
  },
  // -------------------------------------------------
  // 1. کالا (base entity – always created first)
  // -------------------------------------------------
  {
    name: 'کالا',
    description: 'لیست تمام کالاهای موجود در انبار',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام کالا', required: true },
      { id: '2', type: 'text', label: 'بارکد', required: false },
      { id: '3', type: 'number', label: 'موجودی فعلی', required: true },
      { id: '4', type: 'currency', label: 'قیمت خرید', required: true },
      { id: '5', type: 'currency', label: 'قیمت فروش', required: true },
      { id: '6', type: 'text', label: 'واحد', required: true },
    ],
    itemFields: [],
    dependencies: [],
  },

  // -------------------------------------------------
  // 2. سند انبار (references کالا)
  // -------------------------------------------------
  {
    name: 'سند انبار',
    description: 'ثبت ورود/خروج کالا از انبار',
    hasItems: true, // <-- مهم
    headerFields: [
      { id: '1', type: 'date', label: 'تاریخ سند', required: true },
      { id: '2', type: 'text', label: 'شماره سند', required: true },
      {
        id: '3',
        type: 'select',
        label: 'نوع سند',
        options: ['ورود', 'خروج'],
        required: true,
      },
      { id: '4', type: 'textarea', label: 'توضیحات', required: false },
    ],
    itemFields: [
      {
        id: '5',
        type: 'entity_reference',
        label: 'کالا',
        targetFormType: '{step_1_id}',
        displayField: 'نام کالا',
        required: true,
      },
      { id: '6', type: 'number', label: 'تعداد', required: true },
      { id: '7', type: 'text', label: 'واحد', required: true },
      { id: '8', type: 'textarea', label: 'توضیحات ردیف', required: false },
    ],
    dependencies: [{ from: 'کالا', step: '1' }],
  },
  // ERP Examples (16-30)
  {
    name: 'انبار',
    description: 'مدیریت موجودی',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام کالا', required: true },
      { id: '2', type: 'number', label: 'موجودی', required: true },
      { id: '3', type: 'currency', label: 'قیمت خرید', required: true },
      { id: '4', type: 'currency', label: 'قیمت فروش', required: true },
      {
        id: '5',
        type: 'entity_reference',
        label: 'دسته',
        targetFormType: '{step_16_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'دسته‌بندی محصولات', step: '16' }],
  },
  {
    name: 'تامین‌کنندگان',
    description: 'اطلاعات تامین‌کنندگان',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام شرکت', required: true },
      { id: '2', type: 'text', label: 'شماره تماس', required: true },
      { id: '3', type: 'text', label: 'ایمیل', required: true },
      { id: '4', type: 'text', label: 'آدرس', required: false },
      {
        id: '5',
        type: 'select',
        label: 'وضعیت',
        options: ['فعال', 'غیرفعال'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'سفارشات خرید',
    description: 'سفارشات از تامین‌کنندگان',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'تامین‌کننده',
        targetFormType: '{step_17_id}',
        displayField: 'نام شرکت',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ سفارش', required: true },
      { id: '3', type: 'text', label: 'شماره', required: true },
      { id: '4', type: 'currency', label: 'مجموع', required: false },
    ],
    itemFields: [
      {
        id: '5',
        type: 'entity_reference',
        label: 'کالا',
        targetFormType: '{step_16_id}',
        displayField: 'نام کالا',
        required: true,
      },
      { id: '6', type: 'number', label: 'تعداد', required: true },
      { id: '7', type: 'currency', label: 'قیمت واحد', required: true },
      { id: '8', type: 'currency', label: 'جمع', required: false },
    ],
    dependencies: [
      { from: 'انبار', step: '16' },
      { from: 'تامین‌کنندگان', step: '17' },
    ],
  },
  {
    name: 'سفارشات فروش',
    description: 'سفارشات مشتریان',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'مشتری',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      { id: '3', type: 'text', label: 'شماره', required: true },
      { id: '4', type: 'currency', label: 'مجموع', required: false },
    ],
    itemFields: [
      {
        id: '5',
        type: 'entity_reference',
        label: 'کالا',
        targetFormType: '{step_16_id}',
        displayField: 'نام کالا',
        required: true,
      },
      { id: '6', type: 'number', label: 'تعداد', required: true },
      { id: '7', type: 'currency', label: 'قیمت', required: true },
      { id: '8', type: 'currency', label: 'جمع', required: false },
    ],
    dependencies: [
      { from: 'مشتریان', step: '1' },
      { from: 'انبار', step: '16' },
    ],
  },
  {
    name: 'اسناد حسابداری',
    description: 'ثبت اسناد',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'تاریخ', required: true },
      { id: '2', type: 'text', label: 'شرح سند', required: true },
      {
        id: '3',
        type: 'select',
        label: 'نوع',
        options: ['درآمد', 'هزینه', 'انتقال'],
        required: true,
      },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'حساب', required: true },
      { id: '5', type: 'currency', label: 'مبلغ', required: true },
      {
        id: '6',
        type: 'select',
        label: 'بدهکار/بستانکار',
        options: ['بدهکار', 'بستانکار'],
        required: true,
      },
    ],
    dependencies: [],
  },
  {
    name: 'حقوق و دستمزد',
    description: 'پرداخت حقوق',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'ماه', required: true },
      { id: '2', type: 'currency', label: 'مجموع پرداختی', required: false },
    ],
    itemFields: [
      {
        id: '3',
        type: 'entity_reference',
        label: 'کارمند',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '4', type: 'currency', label: 'حقوق پایه', required: true },
      { id: '5', type: 'currency', label: 'اضافه‌کاری', required: false },
      { id: '6', type: 'currency', label: 'کسورات', required: false },
      { id: '7', type: 'currency', label: 'خالص', required: true },
    ],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'بودجه‌بندی',
    description: 'برنامه‌ریزی بودجه',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'سال', required: true },
      {
        id: '2',
        type: 'select',
        label: 'دپارتمان',
        options: ['فروش', 'IT', 'HR'],
        required: true,
      },
    ],
    itemFields: [
      { id: '3', type: 'text', label: 'مورد', required: true },
      { id: '4', type: 'currency', label: 'تخصیص‌یافته', required: true },
      { id: '5', type: 'currency', label: 'مصرف‌شده', required: false },
      { id: '6', type: 'currency', label: 'باقی‌مانده', required: false },
    ],
    dependencies: [],
  },
  {
    name: 'دارایی‌های ثابت',
    description: 'مدیریت دارایی‌ها',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام دارایی', required: true },
      { id: '2', type: 'date', label: 'تاریخ خرید', required: true },
      { id: '3', type: 'currency', label: 'ارزش', required: true },
      { id: '4', type: 'text', label: 'وضعیت', required: true },
      {
        id: '5',
        type: 'entity_reference',
        label: 'دپارتمان',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'دپارتمان‌ها', step: '1' }],
  },
  {
    name: 'مراکز هزینه',
    description: 'پیگیری هزینه‌ها',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام مرکز', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
      {
        id: '3',
        type: 'select',
        label: 'نوع',
        options: ['ثابت', 'متغیر'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'حساب‌های دفتر کل',
    description: 'حسابداری GL',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'شماره حساب', required: true },
      { id: '2', type: 'text', label: 'نام حساب', required: true },
      {
        id: '3',
        type: 'select',
        label: 'نوع حساب',
        options: ['دارایی', 'بدهی'],
        required: true,
      },
      {
        id: '4',
        type: 'entity_reference',
        label: 'مرتبط با مرکز هزینه',
        targetFormType: '{step_20_id}',
        displayField: 'نام مرکز',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'مراکز هزینه', step: '20' }],
  },
  {
    name: 'پرداخت‌های تامین‌کننده',
    description: 'پرداخت به وندورها',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'تامین‌کننده',
        targetFormType: '{step_17_id}',
        displayField: 'نام شرکت',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ پرداخت', required: true },
      { id: '3', type: 'currency', label: 'مبلغ', required: true },
      { id: '4', type: 'text', label: 'روش پرداخت', required: true },
      {
        id: '5',
        type: 'entity_reference',
        label: 'مرتبط با فاکتور',
        targetFormType: '{step_30_id}',
        displayField: 'شماره',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [
      { from: 'تامین‌کنندگان', step: '17' },
      { from: 'فاکتورهای تامین', step: '30' },
    ],
  },
  {
    name: 'تسویه حساب',
    description: 'تسویه اسناد',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'سند',
        targetFormType: '{step_19_id}',
        displayField: 'شرح سند',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ تسویه', required: true },
      { id: '3', type: 'currency', label: 'مبلغ تسویه', required: true },
      { id: '4', type: 'text', label: 'یادداشت', required: false },
    ],
    itemFields: [],
    dependencies: [{ from: 'اسناد حسابداری', step: '19' }],
  },
  {
    name: 'ردیابی حسابرسی',
    description: 'لاگ حسابرسی',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'تاریخ', required: true },
      { id: '2', type: 'text', label: 'نوع حسابرسی', required: true },
    ],
    itemFields: [
      { id: '3', type: 'text', label: 'اقدام', required: true },
      { id: '4', type: 'text', label: 'کاربر', required: true },
      { id: '5', type: 'text', label: 'جزئیات', required: false },
    ],
    dependencies: [],
  },
  {
    name: 'لاگ انطباق',
    description: 'پیگیری قوانین',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'date', label: 'تاریخ', required: true },
      { id: '2', type: 'text', label: 'قانون', required: true },
      { id: '3', type: 'text', label: 'وضعیت انطباق', required: true },
      { id: '4', type: 'textarea', label: 'یادداشت', required: false },
    ],
    itemFields: [],
    dependencies: [],
  },

  // Productivity Examples (31-45)
  {
    name: 'وظایف',
    description: 'مدیریت وظایف',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان', required: true },
      { id: '2', type: 'textarea', label: 'توضیحات', required: false },
      { id: '3', type: 'date', label: 'موعد', required: true },
      {
        id: '4',
        type: 'select',
        label: 'اولویت',
        options: ['بالا', 'متوسط', 'پایین'],
        required: true,
      },
      {
        id: '5',
        type: 'select',
        label: 'وضعیت',
        options: ['در حال انجام', 'تمام شده'],
        required: true,
      },
      {
        id: '6',
        type: 'entity_reference',
        label: 'پروژه',
        targetFormType: '{step_31_id}',
        displayField: 'عنوان',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'پروژه‌ها', step: '31' }],
  },
  {
    name: 'پروژه‌ها',
    description: 'مدیریت پروژه‌ها',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان', required: true },
      { id: '2', type: 'date', label: 'شروع', required: true },
      { id: '3', type: 'date', label: 'پایان', required: true },
      {
        id: '4',
        type: 'select',
        label: 'وضعیت',
        options: ['در حال انجام', 'تمام شده'],
        required: true,
      },
    ],
    itemFields: [
      { id: '5', type: 'text', label: 'مرحله', required: true },
      { id: '6', type: 'date', label: 'موعد', required: true },
    ],
    dependencies: [],
  },
  {
    name: 'رویدادهای تقویم',
    description: 'رویدادهای روزانه',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان', required: true },
      { id: '2', type: 'date', label: 'شروع', required: true },
      { id: '3', type: 'date', label: 'پایان', required: true },
      {
        id: '4',
        type: 'select',
        label: 'نوع',
        options: ['جلسه', 'رویداد'],
        required: true,
      },
      {
        id: '5',
        type: 'entity_reference',
        label: 'مرتبط با پروژه',
        targetFormType: '{step_32_id}',
        displayField: 'عنوان',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'پروژه‌ها', step: '32' }],
  },
  {
    name: 'یادداشت‌ها',
    description: 'یادداشت‌های سریع',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'textarea', label: 'محتوا', required: true },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرتبط با وظیفه',
        targetFormType: '{step_31_id}',
        displayField: 'عنوان',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'وظایف', step: '31' }],
  },
  {
    name: 'دانش‌نامه',
    description: 'مقالات دانش',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان', required: true },
      { id: '2', type: 'textarea', label: 'محتوا', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'دسته',
        targetFormType: '{step_34_id}',
        displayField: 'نام',
        required: false,
      },
      {
        id: '4',
        type: 'select',
        label: 'وضعیت',
        options: ['پیش‌نویس', 'منتشر'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'دسته‌بندی مقالات', step: '34' }],
  },
  {
    name: 'تیم‌ها',
    description: 'مدیریت تیم‌ها',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'نام تیم', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
      {
        id: '3',
        type: 'select',
        label: 'وضعیت',
        options: ['فعال', 'غیرفعال'],
        required: true,
      },
    ],
    itemFields: [
      {
        id: '4',
        type: 'entity_reference',
        label: 'عضو',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      {
        id: '5',
        type: 'select',
        label: 'نقش',
        options: ['مدیر', 'عضو'],
        required: true,
      },
    ],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'پیام‌ها',
    description: 'چت داخلی',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'فرستنده',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      {
        id: '2',
        type: 'entity_reference',
        label: 'گیرنده',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '3', type: 'textarea', label: 'پیام', required: true },
      { id: '4', type: 'date', label: 'زمان', required: true },
    ],
    itemFields: [],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'ردیابی زمان',
    description: 'زمان‌سنجی',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'وظیفه',
        targetFormType: '{step_31_id}',
        displayField: 'عنوان',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'کاربر',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
    ],
    itemFields: [
      { id: '4', type: 'time', label: 'شروع', required: true },
      { id: '5', type: 'time', label: 'پایان', required: true },
      { id: '6', type: 'text', label: 'یادداشت', required: false },
    ],
    dependencies: [{ from: 'وظایف', step: '31' }],
  },
  {
    name: 'اهداف',
    description: 'OKRها',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان هدف', required: true },
      { id: '2', type: 'date', label: 'دوره', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'تیم',
        targetFormType: '{step_36_id}',
        displayField: 'نام تیم',
        required: true,
      },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'KPI', required: true },
      { id: '5', type: 'number', label: 'هدف', required: true },
      { id: '6', type: 'number', label: 'پیشرفت', required: false },
    ],
    dependencies: [{ from: 'تیم‌ها', step: '36' }],
  },
  {
    name: 'بازخوردها',
    description: 'فرم بازخورد',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'کاربر',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'textarea', label: 'بازخورد', required: true },
      {
        id: '3',
        type: 'select',
        label: 'نوع',
        options: ['مثبت', 'منفی'],
        required: true,
      },
      { id: '4', type: 'date', label: 'تاریخ', required: true },
    ],
    itemFields: [],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'تایید اسناد',
    description: 'فرآیند تایید',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'سند',
        targetFormType: '{step_1_id}',
        displayField: 'عنوان',
        required: true,
      },
      {
        id: '2',
        type: 'entity_reference',
        label: 'تصویب‌کننده',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      {
        id: '3',
        type: 'select',
        label: 'تصمیم',
        options: ['تایید', 'رد'],
        required: true,
      },
      { id: '4', type: 'textarea', label: 'دلیل', required: false },
    ],
    itemFields: [],
    dependencies: [
      { from: 'اسناد', step: '1' },
      { from: 'منابع انسانی', step: '31' },
    ],
  },
  {
    name: 'گزارش هزینه',
    description: 'ثبت هزینه‌ها',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'کاربر',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      { id: '3', type: 'text', label: 'توضیحات', required: true },
      { id: '4', type: 'currency', label: 'مبلغ', required: true },
      {
        id: '5',
        type: 'select',
        label: 'دسته',
        options: ['سفر', 'تجهیزات'],
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'درخواست سفر',
    description: 'درخواستهای سفر',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'کاربر',
        targetFormType: '{step_31_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'شروع سفر', required: true },
      { id: '3', type: 'date', label: 'پایان سفر', required: true },
      { id: '4', type: 'text', label: 'مقصد', required: true },
      { id: '5', type: 'currency', label: 'بودجه تخمینی', required: true },
    ],
    itemFields: [],
    dependencies: [{ from: 'منابع انسانی', step: '31' }],
  },
  {
    name: 'صورت‌جلسات',
    description: 'یادداشت جلسات',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان جلسه', required: true },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرتبط با پروژه',
        targetFormType: '{step_32_id}',
        displayField: 'عنوان',
        required: false,
      },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'مورد بحث', required: true },
      { id: '5', type: 'text', label: 'تصمیم', required: false },
    ],
    dependencies: [{ from: 'پروژه‌ها', step: '32' }],
  },
  {
    name: 'اتوماسیون گردش‌کار',
    description: 'تعریف گردش‌کارها',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'نام گردش', required: true },
      { id: '2', type: 'text', label: 'توضیحات', required: false },
      {
        id: '3',
        type: 'entity_reference',
        label: 'مرتبط با فرم',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'گام', required: true },
      {
        id: '5',
        type: 'select',
        label: 'نوع گام',
        options: ['تصویب', 'اطلاع‌رسانی'],
        required: true,
      },
    ],
    dependencies: [{ from: 'فرم‌های سفارشی', step: '1' }],
  },

  // HR Examples (46-50)
  {
    name: 'کارکنان',
    description: 'اطلاعات کارکنان',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام', required: true },
      { id: '2', type: 'text', label: 'نام خانوادگی', required: true },
      { id: '3', type: 'date', label: 'تاریخ استخدام', required: true },
      { id: '4', type: 'text', label: 'دپارتمان', required: true },
      { id: '5', type: 'currency', label: 'حقوق', required: true },
      {
        id: '6',
        type: 'entity_reference',
        label: 'مدیر',
        targetFormType: '{step_46_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'کارکنان', step: '46' }],
  },
  {
    name: 'جذب',
    description: 'فرآیند استخدام',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان شغل', required: true },
      { id: '2', type: 'date', label: 'تاریخ انتشار', required: true },
      { id: '3', type: 'text', label: 'توضیحات', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'نام متقاضی', required: true },
      { id: '5', type: 'text', label: 'رزومه', required: true },
      {
        id: '6',
        type: 'select',
        label: 'وضعیت',
        options: ['مصاحبه', 'پذیرش'],
        required: true,
      },
    ],
    dependencies: [],
  },
  {
    name: 'ارزیابی عملکرد',
    description: 'بررسی عملکرد',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'کارمند',
        targetFormType: '{step_46_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'دوره', required: true },
      { id: '3', type: 'text', label: 'ارزیاب', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'معیار', required: true },
      {
        id: '5',
        type: 'select',
        label: 'امتیاز',
        options: ['عالی', 'خوب'],
        required: true,
      },
      { id: '6', type: 'textarea', label: 'نظرات', required: false },
    ],
    dependencies: [{ from: 'کارکنان', step: '46' }],
  },
  {
    name: 'آموزش',
    description: 'برنامه‌های آموزشی',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'عنوان دوره', required: true },
      { id: '2', type: 'date', label: 'شروع', required: true },
      { id: '3', type: 'date', label: 'پایان', required: true },
    ],
    itemFields: [
      {
        id: '4',
        type: 'entity_reference',
        label: 'شرکت‌کننده',
        targetFormType: '{step_46_id}',
        displayField: 'نام',
        required: true,
      },
      {
        id: '5',
        type: 'select',
        label: 'وضعیت',
        options: ['حاضر', 'غایب'],
        required: true,
      },
      { id: '6', type: 'text', label: 'بازخورد', required: false },
    ],
    dependencies: [{ from: 'کارکنان', step: '46' }],
  },
  {
    name: 'خروج کارکنان',
    description: 'مدیریت خروج',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'کارمند',
        targetFormType: '{step_46_id}',
        displayField: 'نام',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ خروج', required: true },
      { id: '3', type: 'text', label: 'دلیل', required: true },
      { id: '4', type: 'textarea', label: 'یادداشت', required: false },
    ],
    itemFields: [],
    dependencies: [{ from: 'کارکنان', step: '46' }],
  },

  // Finance Examples (51-55)
  {
    name: 'وام‌ها',
    description: 'مدیریت وام‌ها',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'شماره وام', required: true },
      { id: '2', type: 'currency', label: 'مبلغ', required: true },
      { id: '3', type: 'date', label: 'شروع', required: true },
      { id: '4', type: 'date', label: 'پایان', required: true },
      {
        id: '5',
        type: 'entity_reference',
        label: 'گیرنده',
        targetFormType: '{step_1_id}',
        displayField: 'نام',
        required: true,
      },
    ],
    itemFields: [],
    dependencies: [{ from: 'مشتریان', step: '1' }],
  },
  {
    name: 'سرمایه‌گذاری‌ها',
    description: 'پیگیری سرمایه‌گذاری',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'text', label: 'نام سرمایه', required: true },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      { id: '3', type: 'currency', label: 'مبلغ', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'نوع', required: true },
      { id: '5', type: 'currency', label: 'سود', required: false },
      { id: '6', type: 'date', label: 'موعد بازده', required: false },
    ],
    dependencies: [],
  },
  {
    name: 'اظهارنامه مالیاتی',
    description: 'ثبت مالیات',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'date', label: 'سال مالی', required: true },
      { id: '2', type: 'currency', label: 'درآمد کل', required: true },
      { id: '3', type: 'currency', label: 'هزینه‌ها', required: true },
      { id: '4', type: 'currency', label: 'مالیات', required: true },
      { id: '5', type: 'textarea', label: 'جزئیات', required: false },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'صورت‌های مالی',
    description: 'گزارش‌های مالی',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'دوره', required: true },
      {
        id: '2',
        type: 'select',
        label: 'نوع صورت',
        options: ['ترازنامه', 'سود و زیان'],
        required: true,
      },
    ],
    itemFields: [
      { id: '3', type: 'text', label: 'حساب', required: true },
      { id: '4', type: 'currency', label: 'مبلغ', required: true },
      { id: '5', type: 'text', label: 'توضیح', required: false },
    ],
    dependencies: [],
  },
  {
    name: 'پیش‌بینی مالی',
    description: 'پیش‌بینی بودجه',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'ماه', required: true },
      { id: '2', type: 'currency', label: 'پیش‌بینی درآمد', required: true },
      { id: '3', type: 'currency', label: 'پیش‌بینی هزینه', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'دسته', required: true },
      { id: '5', type: 'currency', label: 'جزئیات', required: true },
    ],
    dependencies: [],
  },

  // Supply Chain Examples (56-60)
  {
    name: 'ارسالیه‌ها',
    description: 'مدیریت ارسال',
    hasItems: false,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'سفارش',
        targetFormType: '{step_18_id}',
        displayField: 'شماره',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ ارسال', required: true },
      { id: '3', type: 'text', label: 'شماره بارنامه', required: true },
      { id: '4', type: 'text', label: 'وضعیت', required: true },
      {
        id: '5',
        type: 'entity_reference',
        label: 'حامل',
        targetFormType: '{step_56_id}',
        displayField: 'نام',
        required: false,
      },
    ],
    itemFields: [],
    dependencies: [
      { from: 'سفارشات فروش', step: '18' },
      { from: 'حامل‌ها', step: '56' },
    ],
  },
  {
    name: 'انبارداری',
    description: 'ورود/خروج انبار',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'سفارش',
        targetFormType: '{step_18_id}',
        displayField: 'شماره',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ', required: true },
      { id: '3', type: 'text', label: 'نوع', required: true },
    ],
    itemFields: [
      {
        id: '4',
        type: 'entity_reference',
        label: 'کالا',
        targetFormType: '{step_16_id}',
        displayField: 'نام کالا',
        required: true,
      },
      { id: '5', type: 'number', label: 'تعداد', required: true },
    ],
    dependencies: [
      { from: 'سفارشات فروش', step: '18' },
      { from: 'انبار', step: '16' },
    ],
  },
  {
    name: 'حامل‌ها',
    description: 'شرکت‌های حمل',
    hasItems: false,
    headerFields: [
      { id: '1', type: 'text', label: 'نام شرکت', required: true },
      { id: '2', type: 'text', label: 'شماره تماس', required: true },
      { id: '3', type: 'text', label: 'نوع حمل', required: true },
      { id: '4', type: 'text', label: 'مناطق', required: false },
    ],
    itemFields: [],
    dependencies: [],
  },
  {
    name: 'بازرسی تامین‌کننده',
    description: 'ارزیابی وندورها',
    hasItems: true,
    headerFields: [
      {
        id: '1',
        type: 'entity_reference',
        label: 'تامین‌کننده',
        targetFormType: '{step_17_id}',
        displayField: 'نام شرکت',
        required: true,
      },
      { id: '2', type: 'date', label: 'تاریخ بازرسی', required: true },
      { id: '3', type: 'text', label: 'بازرس', required: true },
    ],
    itemFields: [
      { id: '4', type: 'text', label: 'معیار', required: true },
      {
        id: '5',
        type: 'select',
        label: 'امتیاز',
        options: ['عالی', 'خوب'],
        required: true,
      },
      { id: '6', type: 'textarea', label: 'نظرات', required: false },
    ],
    dependencies: [{ from: 'تامین‌کنندگان', step: '17' }],
  },
  {
    name: 'پیش‌بینی تقاضا',
    description: 'پیش‌بینی انبار',
    hasItems: true,
    headerFields: [
      { id: '1', type: 'date', label: 'دوره', required: true },
      { id: '2', type: 'text', label: 'دسته کالا', required: true },
    ],
    itemFields: [
      {
        id: '3',
        type: 'entity_reference',
        label: 'کالا',
        targetFormType: '{step_16_id}',
        displayField: 'نام کالا',
        required: true,
      },
      { id: '4', type: 'number', label: 'تقاضای پیش‌بینی', required: true },
      { id: '5', type: 'number', label: 'موجودی فعلی', required: false },
    ],
    dependencies: [{ from: 'انبار', step: '16' }],
  },
];
